using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NextMapper.Engine
{

    [Generator]
    public class MappingSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var methodDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is MethodDeclarationSyntax m && m.Modifiers.Any(mod => mod.ValueText == "partial"),
                    transform: static (ctx, _) => GetMappingContext(ctx))
                .Where(static m => m != null);

            context.RegisterSourceOutput(methodDeclarations.Collect(), ExecuteCodeGeneration);
        }

        private static MappingMethodContext GetMappingContext(GeneratorSyntaxContext ctx)
        {
            var methodSyntax = (MethodDeclarationSyntax)ctx.Node;
            var methodSymbol = ctx.SemanticModel.GetDeclaredSymbol(methodSyntax) as IMethodSymbol;
            if (methodSymbol == null) return null;

            var encloserClass = methodSymbol.ContainingType;
            if (!encloserClass.GetAttributes().Any(a => a.AttributeClass?.Name == "MapperAttribute")) return null;

            return new MappingMethodContext(encloserClass, methodSymbol);
        }

        private static void ExecuteCodeGeneration(SourceProductionContext context, ImmutableArray<MappingMethodContext> methods)
        {
            if (methods.IsEmpty) return;

            foreach (var group in methods.GroupBy(m => m.EncloserClass, SymbolEqualityComparer.Default))
            {
                var classSymbol = (INamedTypeSymbol)group.Key;
                var sourceCode = GenerateMapperClass(classSymbol, group);
                context.AddSource($"{classSymbol.Name}_Mappers.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
        }

        private static string GenerateMapperClass(INamedTypeSymbol mapperClass, IEnumerable<MappingMethodContext> methods)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine($"namespace {mapperClass.ContainingNamespace.ToDisplayString()}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {mapperClass.Name}");
            sb.AppendLine("    {");

            foreach (var ctx in methods)
            {
                var method = ctx.MethodSymbol;
                var sourceType = method.Parameters.FirstOrDefault()?.Type as INamedTypeSymbol;
                var targetType = method.ReturnType as INamedTypeSymbol;
                if (sourceType == null || targetType == null) continue;

                sb.AppendLine($"        public partial {targetType.ToDisplayString()} {method.Name}({sourceType.ToDisplayString()} source)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (source == null) return null;");
                sb.AppendLine($"            var target = new {targetType.ToDisplayString()}();");

                var explicitMappings = GetExplicitMappings(method);

                foreach (var targetProp in targetType.GetMembers().OfType<IPropertySymbol>().Where(p => !p.IsReadOnly))
                {
                    // Rule 1: Explicit Mappings [MapMember]
                    if (explicitMappings.TryGetValue(targetProp.Name, out var explicitSourceName))
                    {
                        sb.AppendLine($"            target.{targetProp.Name} = source.{explicitSourceName};");
                        continue;
                    }

                    // Rule 2: Direct Mapping (Matching Names)
                    var directProp = sourceType.GetMembers().OfType<IPropertySymbol>().FirstOrDefault(p => p.Name == targetProp.Name);
                    if (directProp != null)
                    {
                        if (directProp.Type.Name == "List" || directProp.Type.TypeKind == TypeKind.Array)
                            sb.AppendLine($"            target.{targetProp.Name} = source.{directProp.Name}?.ToList();");
                        else
                            sb.AppendLine($"            target.{targetProp.Name} = source.{directProp.Name};");
                        continue;
                    }

                    // Rule 3: Automatic Flattening
                    var flattenedProp = FindFlattenedProperty(sourceType, targetProp.Name);
                    if (flattenedProp != null)
                    {
                        sb.AppendLine($"            if (source.{flattenedProp.Value.ParentObject} != null)");
                        sb.AppendLine($"                target.{targetProp.Name} = source.{flattenedProp.Value.ParentObject}.{flattenedProp.Value.ChildProperty};");
                    }
                }

                sb.AppendLine("            return target;");
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static Dictionary<string, string> GetExplicitMappings(IMethodSymbol method)
        {
            var dic = new Dictionary<string, string>();
            foreach (var attr in method.GetAttributes().Where(a => a.AttributeClass?.Name == "MapMemberAttribute"))
            {
                var source = attr.ConstructorArguments[0].Value?.ToString();
                var target = attr.ConstructorArguments[1].Value?.ToString();
                if (source != null && target != null) dic[target] = source;
            }
            return dic;
        }

        private static (string ParentObject, string ChildProperty)? FindFlattenedProperty(INamedTypeSymbol sourceType, string targetName)
        {
            var complexChildren = sourceType.GetMembers().OfType<IPropertySymbol>()
                .Where(p => p.Type.TypeKind == TypeKind.Class && p.Type.SpecialType == SpecialType.None);

            foreach (var prop in complexChildren)
            {
                if (targetName.StartsWith(prop.Name, StringComparison.OrdinalIgnoreCase))
                {
                    var remainder = targetName.Substring(prop.Name.Length);
                    var subProp = prop.Type.GetMembers().OfType<IPropertySymbol>()
                        .FirstOrDefault(p => string.Equals(p.Name, remainder, StringComparison.OrdinalIgnoreCase));
                    if (subProp != null) return (prop.Name, subProp.Name);
                }
            }
            return null;
        }
    }

    internal class MappingMethodContext
    {
        public INamedTypeSymbol EncloserClass { get; }
        public IMethodSymbol MethodSymbol { get; }
        public MappingMethodContext(INamedTypeSymbol c, IMethodSymbol m) { EncloserClass = c; MethodSymbol = m; }
    }
}